# Generated by Django 4.1.3 on 2022-11-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokeMart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreObjeto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('lugar', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('fechaCompra', models.DateField()),
            ],
        ),
    ]
